name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish -r linux-x64 -c Release /p:PublishSingleFile=true --self-contained

  create_release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: v1.0.0 # Replace with the desired tag name
        release_name: Release 1.0.0 # Replace with the desired release name
        body: Release notes for version 1.0.0 # Replace with release notes if needed
        draft: false
        prerelease: false

    - name: Upload Release Asset
      id: upload_asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: /home/runner/work/OptechX.Library.Apps.UpdateTool/OptechX.Library.Apps.UpdateTool/OptechX.Library.Apps.UpdateTool/bin/Release/net7.0/linux-x64/publish/oxlaut.dll
        asset_name: oxlaut.dll
        asset_content_type: application/octet-stream
